name: Makefile publish
permissions: write-all
on:
  push:
    branches: [master]
    tags:
      - v*
  pull_request:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: make
      run: make all
    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
        name: bin
        path: bin/**
      continue-on-error: true
  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
    - name: Download Artifacts
      id: download
      uses: actions/download-artifact@v3
      with:
        path: bin/
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ github.ref_name }}
        draft: true
        prerelease: true
        generate_release_notes: true
        files: "${{ steps.download.outputs.download-path }}/bin/*"
